name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tags:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the target repository
      uses: actions/checkout@v4
      with:
        repository: rep-23tht/dags
        token: ${{ secrets.COMMIT_GITHUB_TOKEN }}
        ref: main
        path: target

    - name: Replace placeholder in deployment file
      env:
        DAG_FILES: "dags.py,dags1.py,dags2.py"
        IMAGE_NAME: yyttg.nginx
        NEW_TAG: 7777
      run: |
        cd target/
        python update_dag.py
        cat dags.py
        cat dags1.py
        cat dags2.py
        
    - name: Push code to github repo
      run: | 
        cd target
        git branch
        ls -al
        git config --global user.email "${{ secrets.EMAIL_ADDRESS_GITHUB }}"
        git config --global user.name "${{ secrets.COMMIT_GITHUB_USERNAME }}"
        git add .
        git commit -m "updated the  tags"
        git push https://${{ secrets.COMMIT_GITHUB_TOKEN }}@github.com/rep-23tht/dags.git
