# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main1" ]
  pull_request:
    branches: [ "main1" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tags:
      runs-on: ubuntu-latest
      steps:
      - name: Clone the target repository
        uses: actions/checkout@v4
        with:
           repository: rep-23tht/dags
           token: ${{ secrets.COMMIT_GITHUB_TOKEN }}
           ref: main
           path: target

      - name: Replace placeholder in deployment file
        env:
          DAG_FILE_PATH: dags.py
          IMAGE_NAME: yyttg.nginx
          NEW_TAG: 111111
        run: |
          ls -al
          cd target/
          git branch
          python update_dag.py
          cat dags.py

             
